name: GitHub Language Bar

description: Creates GitHub Language Bar

inputs:
  gh_token:
    description: 'Repo-scoped Personal Access Token'
    required: false
    default: ''
  readme_path:
    description: 'Path to README to handle'
    required: false
    default: README.md
  log:
    description: 'Whether to log language usage (private repo warning!)'
    required: false
    default: false

runs:
  using: composite
  steps:
    - name: Checkout current repository
      uses: actions/checkout@v4
      with:
        path: base_repo

    - name: Checkout Language Bar repository
      uses: actions/checkout@v4
      with:
        repository: npanuhin/GitHub-Language-Bar
        path: language_bar_repo

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: pip

    - name: Install Python modules
      run: pip install -r language_bar_repo/requirements.txt
      shell: bash

    - name: Create GitHub Language Bar
      run: >
        cd language_bar_repo &&
        python generate_bar.py ../base_repo/${{ inputs.readme_path }} ${{ github.repository }} ${{ inputs.log }} |
          tee output/log.txt
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.gh_token }}

    - name: Store generated files
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ inputs.gh_token }}
        publish_branch: language-bar
        publish_dir: language_bar_repo/output
        exclude_assets: .gitkeep
        force_orphan: true
        disable_nojekyll: true
        user_name: GitHub Actions
        user_email: github-actions[bot]@users.noreply.github.com
        full_commit_message: Updated Language Bar

    # - name: Clear output (generated) files
    #   run: find language_bar_repo/output -type f -not -name '.*' -delete
    #   shell: bash

    - name: Push changes made by script
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        repository: base_repo
        commit_message: 'Language Bar Update'
        commit_user_name: GitHub Actions
        commit_user_email: github-actions[bot]@users.noreply.github.com
        commit_author: GitHub Actions <github-actions[bot]@users.noreply.github.com>
