name: GitHub Language Bar

on:
  push:               # Run every time config or README changes
    paths:
      - README.md
      - .github/workflows/*
  schedule:           # Run every day at to 4:38 AM
    - cron: 38 4 * * *
  workflow_dispatch:  # Run with a button in the Actions tab

jobs:
  language_bar:
    name: Create GitHub Language Bar
    runs-on: ubuntu-latest
    steps:
      - name: Create Language Bar
        uses: npanuhin/GitHub-Language-Bar@master
        # with:
        #   gh_token: ${{ secrets.LANG_BAR_PAT }}
        #   log: true
        #   readme_path: 'path/to/my/awesome/README.md'
